spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/ahmsdlog
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE